### ISSUE TITLE
accessing entitites/models inside interface

### ISSUE THREAD

**Issue by akif-ih** [manakuro/golang-clean-architecture#1]
Hi i just wanted to know why u accessed models inside the interface layer as clean archi said only outer layer know about the next immediate later aren't we voilating the rule ?

**Comment by manakuro** [comment]
Thank you for your question.

The outer layers do not always have to depend on the next layer.  The dependencies should be only inward. So you can use models in any outer layer of it.

**Comment by smithaitufe** [comment]
You should close this issue. @manakuro
