### ISSUE TITLE
Migrations absent

### ISSUE THREAD

**Issue by bernardolm** [manakuro/golang-clean-architecture#11]
```makefile
> make migrate_schema 
go run ./cmd/migration/main.go
stat ./cmd/migration/main.go: no such file or directory
make: *** [Makefile:15: migrate_schema] Error 1
```
I believe you forgot to commit the `cmd/migration` folder.
Could you send those files, please?
I want to run this to use debug and navigate the calls.
Thank you!

**Comment by manakuro** [comment]
@bernardolm Hi, thanks for your report. I merged the change so you can test it out on your local, like so:

Start the docker.
```
$ cd docker
$ docker compose up
```

And set up the database and boot up the server.
```
$ make install
$ make setup_db
$ make migrate_schema_up
$ make seed
$ make start
```

https://github.com/manakuro/golang-clean-architecture/pull/12

**Comment by bernardolm** [comment]
Thank you!
