### ISSUE TITLE
Implementing multiple Controllers

### ISSUE THREAD

**Issue by firasmdar** [manakuro/golang-clean-architecture#2]
in **interface/controller/app_controller.go**:
```
type AppController interface {
	CollectionController
}
```

on **registry/registry.go**, we have the following code:
```
func (r *registry) NewAppController() controller.AppController {
	return r.NewCollectionController()
}
```

which will be used in `main.go` to pass down db instance
```
r := registry.NewRegistry(db)
	e := echo.New()
	e = router.NewRouter(e, r.NewAppController())
```

and it all works perfectly well, but my problem here is that i'm trying to implement **multiple** controllers
```
type AppController interface {
	CollectionController
	DocumentController
}
```

what modifications needs to be done on **func (r *registry) NewAppController() controller.AppController** (**registry/registry.go**) to make it work?

**Comment by manakuro** [comment]
@firasmdar 

Sorry for the late reply.

Can you try to make `AppController` struct type like this?

https://github.com/manakuro/golang-clean-architecture/commit/1c9b1ca29b08e5ff006922b00aef34f639f6dd81

So, you can add other controllers to `AppController`.
