### ISSUE TITLE
Use the interface defined on the internal layer by the external layer.

### ISSUE THREAD

**Issue by goofinator** [manakuro/golang-clean-architecture#5]
I'm not a big specialist, but as far as I understand, the essence of clear architecture is to eliminate the dependence of internal layers on external ones. At the same time, the outer layers must implement the abstractions defined on the inner layers.

If this is the case, I don't quite understand why I have to declare the **UserRepository** interface in _golang-clean-architecture/interface/repository/user_repository.go_, if the method specification is essentially defined in _golang-clean-architecture/usecase/presenter/user_presenter.go_. 

Probably something like that should be done:
```
import (
	...
	"golang-clean-architecture/usecase/presenter"
)

...
func NewUserRepository(db *gorm.DB) presenter.UserPresenter {
	return &userRepository{db}
}
```
Or perhaps you should return the structure.
This will increase the autonomy of the layer's unit - it can be used wherever the signature suits.

However, the first option clearly indicates the direction of dependency.

**Comment by manakuro** [comment]
@goofinator Thank you for your suggestions. 

The repository conforms to usecase in `registry/user_registry.go`.

https://github.com/manakuro/golang-clean-architecture/blob/cc8b0a5e0c631d7b28f66287de1d9826bfedca1a/registry/user_registry.go#L20

But as you said, that **UserRepository** interface can be redundant. 

So, you can use the usecase interface as a return type in `repository/user_repository.go` instead.

https://github.com/manakuro/golang-clean-architecture/commit/fb295bac44754ee8637fae14fffea96f24f4720e

I really appreciate your help anyway!
